version: '3.7'

services:
  db:
    container_name: tourplanner-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: tourplanner
      POSTGRES_USER: tourplanner
      POSTGRES_PASSWORD: tourplanner
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: